title: Lucas Monteiro Inacio # your name (or website title) here
logo: "https://github.com/LucasMonteiroi.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BackEnd Developer
  <br><br>
  <a href="https://www.linkedin.com/in/lucasmonteiroinacio/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
